---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compiler.example.com
  resources:
  - compilerenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compiler.example.com
  resources:
  - compilerenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - compiler.example.com
  resources:
  - compilerenvironments/status
  verbs:
  - get
  - patch
  - update
